<h2 style="font-family: 'Times New Roman', Times, serif; font-size: 18px; margin-bottom: 0;">
Environment Setup
</h2>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 14px; margin-top: 0;">
This section loads the dataset files and imports the necessary libraries required for the project.
</p>

In [ ]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
import os


print("All packages imported successfully ")
ohio_corn_yields_df = pd.read_csv("/workspaces/corn-production-economic-impact/raw_ data/Ohio corn yield.csv")# Ohio state corn yields data from USDA
ohio_unemployment_rate_df = pd.read_csv("/workspaces/corn-production-economic-impact/raw_ data/ohio unemployement.csv")# Ohio state unemployment rate data from FRED
ohio_snap_benefits_df =pd.read_csv("/workspaces/corn-production-economic-impact/raw_ data/ohio snap benefit.csv") # Ohio state snap benefit data from FRED
ohio_population_df = pd.read_csv("/workspaces/corn-production-economic-impact/raw_ data/Ohio population.csv")
clinton_corn_yields_df =pd. read_csv("/workspaces/corn-production-economic-impact/raw_ data/Clinton corn yields.csv") # Clinton county corn yields data from USDA
clinton_unemployment_rate_df = pd.read_csv("/workspaces/corn-production-economic-impact/raw_ data/clinton unemployement.csv")# Clinton county unemployment rate data from FRED
clinton_snap_benefits_df = pd.read_csv("/workspaces/corn-production-economic-impact/raw_ data/clinton snap.csv")# Clinton county snap benefit data from FRED
clinton_population_df = pd.read_csv("/workspaces/corn-production-economic-impact/raw_ data/Clinton population.csv")
print("Data Loaded successfully ")
data_sets = [ohio_corn_yields_df, ohio_unemployment_rate_df, ohio_snap_benefits_df, ohio_population_df, clinton_corn_yields_df,
       clinton_unemployment_rate_df, clinton_snap_benefits_df, clinton_population_df]
for data_set in data_sets:
    print("_______")
    count_missing = data_set.isna().sum()
    print(count_missing)

All packages imported successfully
Data Loaded successfully
_______
Program               0
Year                  0
Period                0
Week Ending         463
Geo Level             0
State                 0
State ANSI            0
Ag District         463
Ag District Code    463
County              463
County ANSI         463
Zip Code            463
Region              463
watershed_code        0
Watershed           463
Commodity             0
Data Item             0
Domain                0
Domain Category       0
Value                 0
CV (%)              463
dtype: int64
_______
observation_date    0
OHUR                1
dtype: int64
_______
observation_date    0
BROH39M647NCEN      0
dtype: int64
_______
observation_date    0
OHPOP               0
dtype: int64
_______
Program               0
Year                  0
Period                0
Week Ending         119
Geo Level             0
State                 0
State ANSI            0
Ag District           0
Ag District Code      0
County                0
County ANSI           0
Zip Code            119
Region              119
watershed_code        0
Watershed           119
Commodity             0
Data Item             0
Domain                0
Domain Category       0
Value                 0
CV (%)              114
dtype: int64
_______
observation_date    0
OHCLIN7URN          1
dtype: int64
_______
observation_date      0
CBR39027OHA647NCEN    0
dtype: int64
_______
observation_date    0
OHCLIN7POP          0
dtype: int64

<p style="font-family: 'Times New Roman', Times, serif; font-size: 14px; margin-top: 0;">
This section selects columns that I am going to use for analyisis
</p>

In [ ]:
#Only the corn yield data has some extra that is not needed so drop them.
data_needed_ohio = ["Year","Period", "State", "Commodity", "Data Item", "Value", "CV (%)"]
data_needed_clinton = ["Year","Period", "County", "Commodity", "Data Item", "Value", "CV (%)"]
ohio_corn_yields_df = ohio_corn_yields_df[data_needed_ohio]
clinton_corn_yields_df = clinton_corn_yields_df[data_needed_clinton]
clinton_corn_yields_df

,Year,Period,County,Commodity,Data Item,Value,CV (%)
0,2024,YEAR,CLINTON,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",207.6,1.3
1,2023,YEAR,CLINTON,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",222.1,2.9
2,2022,YEAR,CLINTON,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",196.2,2.9
3,2021,YEAR,CLINTON,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",210.3,2.6
4,2020,YEAR,CLINTON,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",199.8,1.5
...,...,...,...,...,...,...,...
114,1922,YEAR,CLINTON,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",43.7,NaN
115,1921,YEAR,CLINTON,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",37.6,NaN
116,1920,YEAR,CLINTON,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",42.4,NaN
117,1919,YEAR,CLINTON,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",46.2,NaN
118,1918,YEAR,CLINTON,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",38.8,NaN

<p style="font-family: 'Times New Roman', Times, serif; font-size: 14px; margin-top: 0;">
This section renames columns and indexes to be more descriptive
</p>

In [ ]:


# Clinton county unemployment rate monthly data columns renaming
clinton_unemployment_rate_df = clinton_unemployment_rate_df.rename(columns={"OHCLIN7URN":"Unemployment_Rate_Clinton", "observation_date": "Observation_Date_Monthly"})

# Ohio state unemployment rate monthly data columns renaming
ohio_unemployment_rate_df = ohio_unemployment_rate_df.rename(columns={"OHUR": "Unemployment_Rate_Ohio", "observation_date": "Observation_Date_Monthly"})

# Clinton snap recipients monthly data columns renaming
#Note: said monthly data but its its anual, will update in later sections to be monthly 
clinton_snap_benefits_df = clinton_snap_benefits_df.rename(columns={"CBR39027OHA647NCEN": "Number_Of_Snap_Recipients_Clinton", "observation_date": "Observation_Date_Monthly"})

#Ohio snap recipients monthly data columns renaming
ohio_snap_benefits_df = ohio_snap_benefits_df.rename(columns={"BROH39M647NCEN":"Number_Of_Snap_Recipients_Ohio", "observation_date": "Observation_Date_Monthly"})

#Clinton corn yield monthly data columns renaming
#Note: said monthly data but its its anual, will update in later sections to be monthly 
clinton_corn_yields_df = clinton_corn_yields_df.rename(columns = {"Year": "Observation_Date_Monthly", "Data Item": "Data_Item"})

#Ohio corn yield monthly data columns renaming
#Note: said monthly data but its its anual, will update in later sections to be monthly 
ohio_corn_yields_df = ohio_corn_yields_df.rename(columns = {"Year": "Observation_Date_Monthly", "Data Item": "Data_Item"})
ohio_snap_benefits_df

#Clinton population data renaming
#Note: said monthly data but its its anual, will update in later sections to be monthly 
clinton_population_df = clinton_population_df.rename(columns={"observation_date": "Observation_Date_Monthly", "OHCLIN7POP": "Clinton_Population_In_Thousands"})

#Clinton population data renaming
#Note: said monthly data but its its anual, will update in later sections to be monthly 
ohio_population_df = ohio_population_df.rename(columns={"observation_date": "Observation_Date_Monthly", "OHPOP": "Ohio_Population_In_Thousands"})
ohio_corn_yields_df

,Observation_Date_Monthly,Period,State,Commodity,Data_Item,Value,CV (%)
0,2025,YEAR,OHIO,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",185.0,NaN
1,2025,YEAR,OHIO,CORN,"CORN, SILAGE - YIELD, MEASURED IN TONS / ACRE",22.0,NaN
2,2025,YEAR - AUG FORECAST,OHIO,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",196.0,NaN
3,2025,YEAR - NOV FORECAST,OHIO,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",194.0,NaN
4,2025,YEAR - SEP FORECAST,OHIO,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",194.0,NaN
...,...,...,...,...,...,...,...
458,1870,YEAR,OHIO,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",39.0,NaN
459,1869,YEAR,OHIO,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",30.0,NaN
460,1868,YEAR,OHIO,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",35.0,NaN
461,1867,YEAR,OHIO,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",30.0,NaN
462,1866,YEAR,OHIO,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",37.0,NaN

<p style="font-family: 'Times New Roman', Times, serif; font-size: 14px; margin-top: 0;">
This section ensures that the dates across all datasets are aligned so that they are consistent for analysis. The data used in this study is monthly and spans from January 2001 to June 2024. The formatt desired is one similar to the Ohio Snap benefit data
</p>

In [ ]:
# Rename for example from this format(2023-06-01) to just June 2024

#For ohio snap benefit
# Check first value to determine format
sample = ohio_snap_benefits_df["Observation_Date_Monthly"].dropna().iloc[0]
if "-" in str(sample):
    ohio_snap_benefits_df["Observation_Date_Monthly"] = pd.to_datetime(ohio_snap_benefits_df["Observation_Date_Monthly"],format="%Y-%m-%d").dt.strftime("%B %Y")
else: 
    ohio_snap_benefits_df["Observation_Date_Monthly"] = pd.to_datetime(ohio_snap_benefits_df["Observation_Date_Monthly"],format="%B %Y").dt.strftime("%B %Y")
ohio_snap_benefits_df_clean = ohio_snap_benefits_df


# Clinton County SNAP Benefits Processing
# 1. Add missing 2024 estimate if it doesn't exist
if not (clinton_snap_benefits_df["Observation_Date_Monthly"] == "2024-01-01").any():
    clinton_snap_mean = clinton_snap_benefits_df["Number_Of_Snap_Recipients_Clinton"].mean()
    new_row = pd.DataFrame({"Observation_Date_Monthly": ["2024-01-01"],"Number_Of_Snap_Recipients_Clinton": [clinton_snap_mean]})
    clinton_snap_benefits_df = pd.concat([clinton_snap_benefits_df, new_row],ignore_index=True)
# 2. Ensure one row per year
clinton_snap_benefits_df = clinton_snap_benefits_df.drop_duplicates(subset="Observation_Date_Monthly")
# 3. Only expand to monthly to fill years if not already expanded 
if len(clinton_snap_benefits_df) < len(ohio_snap_benefits_df):
    clinton_snap_benefits_df = (clinton_snap_benefits_df.loc[clinton_snap_benefits_df.index.repeat(12)].reset_index(drop=True) )
clinton_snap_benefits_df_clean = clinton_snap_benefits_df.drop(clinton_snap_benefits_df.tail(6).index)
clinton_snap_benefits_df_clean["Observation_Date_Monthly"] = ohio_snap_benefits_df_clean["Observation_Date_Monthly"]
clinton_snap_benefits_df_clean

#For ohio unemployment 
ohio_unemployment_rate_df.drop_duplicates(subset="Observation_Date_Monthly", inplace=True)
ohio_unemployment_rate_df_clean = ohio_unemployment_rate_df.drop(ohio_unemployment_rate_df.tail(18).index)
ohio_unemployment_rate_df_clean["Observation_Date_Monthly"] = ohio_snap_benefits_df_clean["Observation_Date_Monthly"]
ohio_unemployment_rate_df_clean

#For Clinton unemployment 
clinton_unemployment_rate_df.drop_duplicates(subset="Observation_Date_Monthly", inplace=True)
clinton_unemployment_rate_df_clean = clinton_unemployment_rate_df.drop(clinton_unemployment_rate_df.tail(18).index)
clinton_unemployment_rate_df_clean["Observation_Date_Monthly"] = ohio_snap_benefits_df_clean["Observation_Date_Monthly"]
clinton_unemployment_rate_df_clean

#Preview of final dataset
final = pd.concat([ohio_snap_benefits_df_clean,clinton_snap_benefits_df_clean, ohio_unemployment_rate_df_clean, clinton_unemployment_rate_df_clean,], axis = 1)
columns_needed = ["Observation_Date_Monthly", "Number_Of_Snap_Recipients_Ohio", "Number_Of_Snap_Recipients_Clinton", "Unemployment_Rate_Ohio", "Unemployment_Rate_Clinton"]
final_df = final[columns_needed]
final_df = final_df.iloc[:, 3:]


#Ohio corn
ohio_corn_yields_df["Observation_Date_Formated"] = pd.to_datetime(ohio_corn_yields_df["Observation_Date_Monthly"].astype(str), format='%Y')
ohio_corn_yields_df_dates_needed = ohio_corn_yields_df[ohio_corn_yields_df["Observation_Date_Formated"].between("2001-01-01", "2024-01-01")]
#Drop data with silage we only want grain
ohio_corn_yields_df_grain = ohio_corn_yields_df_dates_needed[ohio_corn_yields_df_dates_needed["Data_Item"].str.contains("GRAIN")]
#Fill data for other (Jan-July) using December Data
repeat_counts = np.where(ohio_corn_yields_df_grain["Period"] == "YEAR", 8, 1)
ohio_corn_yields_df_all_months = ohio_corn_yields_df_grain.loc[ohio_corn_yields_df_grain.index.repeat(repeat_counts)].reset_index(drop = True)
# 2013 is missing October data because there was gorvement shutdown fill that with september data
repeat_counts_2013 = np.where(((ohio_corn_yields_df_all_months["Observation_Date_Monthly"] == 2013) & (ohio_corn_yields_df_all_months["Period"] == "YEAR - SEP FORECAST")), 2, 1)
ohio_corn_yields_df_all_months_final = ohio_corn_yields_df_all_months.loc[ohio_corn_yields_df_all_months.index.repeat(repeat_counts_2013)].reset_index(drop = True)
ohio_corn_yields_df_all_months_final.head(12)
#Now sort months
months_order = {"YEAR": 1, "YEAR - AUG FORECAST": 8, "YEAR - NOV FORECAST": 11, "YEAR - OCT FORECAST":10, "YEAR - SEP FORECAST": 9}
ohio_corn_yields_df_all_months_final["Month_Num"] = ohio_corn_yields_df_all_months_final["Period"].map(months_order)
ohio_corn_yields_df_all_months_final = ohio_corn_yields_df_all_months_final.sort_values(by = ["Observation_Date_Monthly", "Month_Num"]).reset_index(drop = True)

#Drop last 6 months to have data from 2001 January to 2024 June
ohio_corn_yields_df_dropped = ohio_corn_yields_df_all_months_final.drop(ohio_corn_yields_df_all_months_final.tail(6).index).reset_index(drop = True)

# Change to the right dates needed 
ohio_corn_yields_df_dropped["Observation_Date_Monthly"] =  ohio_snap_benefits_df_clean["Observation_Date_Monthly"]

#Rename value column
ohio_corn_yields_df_dropped["Ohio_Corn_Grain_Yield_BU/ACRE"] = ohio_corn_yields_df_dropped["Value"]

#Columns needed for analysis
impo_columns =  ["Observation_Date_Monthly","Ohio_Corn_Grain_Yield_BU/ACRE" ]
ohio_corn_yields_df_clean = ohio_corn_yields_df_dropped[impo_columns]
ohio_corn_yields_df_clean.head(12)

#Clinton

# Clinton corn

# Convert year column to datetime
clinton_corn_yields_df["Observation_Date_Formated"] = pd.to_datetime(clinton_corn_yields_df["Observation_Date_Monthly"].astype(str),format="%Y")
# Keep only dates between 2001 and 2024
clinton_corn_yields_df_dates_needed = clinton_corn_yields_df[clinton_corn_yields_df["Observation_Date_Formated"].between("2001-01-01", "2024-01-01")]

# Fill data for other months (Jan–Jul) using December data
repeat_counts = np.where(clinton_corn_yields_df_dates_needed["Period"] == "YEAR", 12, 1)
clinton_corn_yields_df_all_months = (clinton_corn_yields_df_dates_needed.loc[clinton_corn_yields_df_dates_needed.index.repeat(repeat_counts)].reset_index(drop=True))

# Drop last 6 months so data ends at June 2024
clinton_corn_yields_df_dropped = (clinton_corn_yields_df_all_months.drop(clinton_corn_yields_df_all_months.tail(6).index).reset_index(drop=True))

# Replace with correct monthly dates
clinton_corn_yields_df_dropped["Observation_Date_Monthly"] = ohio_snap_benefits_df_clean["Observation_Date_Monthly"]

# Rename value column
clinton_corn_yields_df_dropped["Clinton_Corn_Grain_Yield_BU/ACRE"] = clinton_corn_yields_df_dropped["Value"]

# Columns needed for analysis
impota_columns = ["Observation_Date_Monthly", "Clinton_Corn_Grain_Yield_BU/ACRE"]
clinton_corn_yields_df_clean = clinton_corn_yields_df_dropped[impota_columns]

#Ohio population
if len(ohio_population_df) < len(ohio_snap_benefits_df):
  ohio_population_df = (ohio_population_df.loc[ohio_population_df.index.repeat(12)].reset_index(drop=True) )
ohio_population_df_clean = ohio_population_df.drop(ohio_population_df.tail(18).index) #has 2025 data so drop data for 2025 and 2024 last months
ohio_population_df["Observation_Date_Monthly"] = ohio_snap_benefits_df_clean["Observation_Date_Monthly"]
#Clinton Population 
#Ohio population
if len(clinton_population_df) < len(ohio_snap_benefits_df):
  clinton_population_df = (clinton_population_df.loc[clinton_population_df.index.repeat(12)].reset_index(drop=True) )
clinton_population_df_clean = clinton_population_df.drop(clinton_population_df.tail(6).index) #has 2024 full so just drop last 6 moths
clinton_population_df["Observation_Date_Monthly"] = ohio_snap_benefits_df_clean["Observation_Date_Monthly"]

#FINAL DATASETS CLEANED
# Ohio dataset
ohio_unemployment_snap_corn_df = pd.concat([ohio_unemployment_rate_df_clean, ohio_snap_benefits_df_clean.drop(columns=["Observation_Date_Monthly"]), 
                                            ohio_corn_yields_df_clean.drop(columns=["Observation_Date_Monthly"]), ohio_population_df_clean.drop(columns=["Observation_Date_Monthly"])],axis=1)
# Clinton County dataset
clinton_unemployment_snap_corn_df = pd.concat([clinton_unemployment_rate_df_clean, clinton_snap_benefits_df_clean.drop(columns=["Observation_Date_Monthly"])
                                               ,clinton_corn_yields_df_clean.drop(columns=["Observation_Date_Monthly"]),clinton_population_df_clean.drop(columns=["Observation_Date_Monthly"])], axis =1)
# Combined Ohio + Clinton dataset
combined_ohio_clinton_df = pd.concat([ohio_unemployment_snap_corn_df,clinton_unemployment_snap_corn_df.drop(columns=["Observation_Date_Monthly"])],
                                     axis=1).reset_index(drop=True)

# Ensure the folder exists
output_folder = "/workspaces/corn-production-economic-impact/processed_clean_data"
os.makedirs(output_folder, exist_ok=True)

# Save the three dataframes as CSV
ohio_unemployment_snap_corn_df.to_csv(f"{output_folder}/ohio_unemployment_snap_corn_df.csv", index=False)
clinton_unemployment_snap_corn_df.to_csv(f"{output_folder}/clinton_unemployment_snap_corn_df.csv", index=False)
combined_ohio_clinton_df.to_csv(f"{output_folder}/combined_ohio_clinton_df.csv", index=False)

print("All three dataframes have been saved successfully!")

All three dataframes have been saved successfully!